name: Build & Deploy Spring app

#when to trigger this piepline
on:
  push:
    branches:
      - main

# pipeline several job have (one job run on seprate machine)
jobs:
  # first job
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    #each job hav diffrent steps
    steps:
      # copy the cod repo copy to runner (ubuntu latest)
      - name: Checkout code
        uses: actions/checkout@v3 # like git clone
# we need install java jdk 17 on runner ()
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
# run unit testing
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: | # clean my target package (run multiple commands want to run)
          mvn clean 
          mvn -B package --file pom.xml
          
#      - name: Build Docker Image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:today
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:today