name: Build & Deploy Spring app

#when to trigger this pieplins
on:
  push:
    branches:
      - main

# pipeline several job have (one job run on seprate machine)
jobs:
  # first job
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    #each job hav diffrent steps
    steps:
      # copy the cod repo copy to runner (ubuntu latest)
      - name: Checkout code
        uses: actions/checkout@v3 # like git clone
# we need install java jdk 17 on runner ()
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
# run unit testing
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: | # clean my target package (run multiple commands want to run)
          mvn clean 
          mvn -B package --file pom.xml
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }} # Fetch Docker username from secrets
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # Fetch Docker password from secrets
        run: echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        # This command logs into Docker Hub using the credentials stored in GitHub Secrets. The password is piped to login securely.

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest .
        # This command builds a Docker image using the current directory (.) and tags it as 'authservice:latest' with the user's Docker Hub username.

      # Step 4: Push the Docker image to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest